#!/bin/bash

cd ~/
rm -rf .vim.bak
mv .vim .vim.bak

# Create .vim with vim-pathogen in it
# git clone https://github.com/tpope/vim-pathogen ~/.vim
mkdir .vim
cd .vim
mkdir autoload
cd autoload
curl -C - -O https://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim

cd ../
mkdir bundle
cd bundle

git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/msanders/snipmate.vim.git
git clone git://github.com/tpope/vim-cucumber.git
git clone git://github.com/tpope/vim-fugitive.git
git clone git://github.com/tpope/vim-markdown.git
git clone git://github.com/tpope/vim-surround.git
git clone git://github.com/tsaleh/vim-tcomment.git

# COLOR SCHEMES
git clone git://github.com/tpope/vim-vividchalk.git #vividchalk
git clone https://github.com/mgutz/vim-colors.git vim-colors-mgutz #underwater-mod, chance-of-storm, southwest-fog
git clone https://github.com/jpo/vim-railscasts-theme.git #railscasts

